import { Inter } from "next/font/google";
import "./globals.css";
import InputProvider from "./context/inputContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ClearCredit",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="main">
        <InputProvider>
        {children}
        </InputProvider>
      </body>
    </html>
  );
}
