import Modal from "@/components/Modal/Modal";
import CompareSection from "./screens/compareSection/page";
import Contact from "./screens/contact/page";
import FAQS from "./screens/faqs/page";
import Footer from "./screens/footer/page";
import Hero from "./screens/hero/page";
import HowItWorks from "./screens/howItWorks/page";
import Navbar from "./screens/navbar/page";
import SavingsCalculator from "./screens/savingsCalculator/page";
import ImageSwiper from "./screens/swiper/swiper";
import TourGoals from "./screens/tourGoals/page";
import WhySection from "./screens/whySection/page";
import Head from "next/head";
import Script from "next/script";

export default function Home() {
  return (
    <main>
{/* <Head>
  <title>Debt Consolidation Loan | ClearCredit</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta
    name="description"
    content="Consolidating debt can help you simplify and take control of your finances. Combine balances and make one set monthly payment with a debt consolidation loan."
  />
  <meta
    name="keywords"
    content="Debt consolidation, consolidate, consolidation loans, debt consolidation loan, debt, how to get out of debt, unsecured debt, debt, personal loans, personal loan"
  />
  <meta name="robots" content="index, follow" />
  <link rel="canonical" href="https://www.wellsfargo.com/personal-loans/debt-consolidation/" />
  <link rel="alternate" href="https://www.wellsfargo.com/personal-loans/debt-consolidation/" hreflang="en-us" />

  <meta property="og:title" content="Debt Consolidation Loan | Clear Credit" />
  <meta
    property="og:description"
    content="Consolidating debt can help you simplify and take control of your finances. Combine balances and make one set monthly payment with a debt consolidation loan."
  />
  <meta
    property="og:image"
    content="https://www.wellsfargo.com/assets/images/photography/lifestyle/970x462/large_marquee_desktop_woman_at_laptop_reclining_970x462.jpg"
  />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="https://www.wellsfargo.com/personal-loans/debt-consolidation/" />
  <meta property="og:site_name" content="Wells Fargo" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:site" content="@ClearCredit" />

  <meta name="description" content="Generated by create next app" />
  <link rel="icon" href="/favicon.ico" />

  <Script
    strategy="lazyOnload"
    dangerouslySetInnerHTML={{
      __html: `
        (function(c,l,a,r,i,t,y){
          c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
          t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
          y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
        })(window, document, "clarity", "script", "kj3s2qcy7x");
      `,
    }}
  />
</Head> */}


      {/* <Modal/> */}
      <Navbar />
      <Hero />
      <ImageSwiper />
      <CompareSection />
      <SavingsCalculator />
      <WhySection />
      <HowItWorks />
      <TourGoals />
      <FAQS />
      <Contact />
      <Footer />
    </main>
  );
}
