const lenders = [
  {
    id: 1,
    img: "/upstartlogo.svg",
    rating: 3.9,
    APR: "6.40-35.99%",
    loanTerm: "3, 5 Years",
    loanAmount: "Up to $50,000",
    details: [
      {
        title: "Upstart",
        Prepaymentpenalty: "None",
        Unsuccessfulpaymentfee: "$15",
        MinimumCreditScore: 620,
        OriginationFee: "0% to 12%",
        Checkprocessingfee: "None",
        Dotheyallowacosigner: "No",
        Latefee: "5% of late payment or $15 (whichever is greater)",
        Timetofund: "As soon as 1 - 3 business days",
        Bestfor: "Fast personal loans for bad credit",
      },
    ],
  },
  {
    id: 2,
    img: "/lendingclublogo.svg",
    rating: 4,
    APR: "9.57-35.99%",
    loanTerm: "2 - 5 years",
    loanAmount: "Up to $40,000",
    details: [
        {
          title: "LendingClub",
          Prepaymentpenalty: "None",
          Unsuccessfulpaymentfee: "$15",
          MinimumCreditScore: 660,
          OriginationFee: "3% to 8%",
          Checkprocessingfee: "$7",
          Dotheyallowacosigner: "No, but co-borrowers allowed",
          Latefee: "5% of late payment or $15 (whichever is greater)",
          Timetofund: "Get funds in as little as 2 days",
          Bestfor: "online experience",
        },
      ],
  },
  {
    id: 3,
    img: "/discoverlogo.svg",
    rating: 4.4,
    APR: "7.99-24.99%",
    loanTerm: "3-7 Years",
    loanAmount: "Up to $40,000",
    details: [
        {
          title: "Discover",
          Prepaymentpenalty: "None",
          Unsuccessfulpaymentfee: "None",
          MinimumCreditScore: 660,
          OriginationFee: "None",
          Checkprocessingfee: "None",
          Dotheyallowacosigner: "No",
          Latefee: "$39",
          Timetofund: "Funds can be sent as soon as the next business day after acceptance",
          Bestfor: "Low interest rate personal loans",
        },
      ],
  },
  {
    id: 4,
    img: "/zablelogo.svg",
    rating: 3.5,
    APR: "8.00-30.00%",
    loanTerm: "1-5 Years",
    loanAmount: "Up to $25,000",
    details: [
        {
          title: "Zable",
          Prepaymentpenalty: "None",
          Unsuccessfulpaymentfee: "None",
          MinimumCreditScore: 600,
          OriginationFee: "5% to 9%",
          Checkprocessingfee: "None",
          Dotheyallowacosigner: "No",
          Latefee: "None",
          Timetofund: "As soon as the same business day if approved by 3:30pm Eastern Time",
          Bestfor: "Short-term loans and same day funding",
        },
      ],
  },
  {
    id: 5,
    img: "/sofilogo.svg",
    rating: 4.9,
    APR: "8.99-25.81%",
    loanTerm: "2-7 Years",
    loanAmount: "Up to $100,000",
    details: [
        {
          title: "Sofi",
          Prepaymentpenalty: "None",
          Unsuccessfulpaymentfee: "None",
          MinimumCreditScore: "Does not disclose",
          OriginationFee: "0% - 6%",
          Checkprocessingfee: "None",
          Dotheyallowacosigner: "No",
          Latefee: "None",
          Timetofund: "Typically within a few days, given approval and bank account verification",
          Bestfor: "personal loans for excellent credit",
        },
      ],
  },
  {
    id: 6,
    img: "/bestegglogo.svg",
    rating: 4,
    APR: "8.99-35.99%",
    loanTerm: "2-5 Years",
    loanAmount: "Up to $50,000",
    details: [
        {
          title: "Best Egg",
          Prepaymentpenalty: "None",
          Unsuccessfulpaymentfee: "$15",
          MinimumCreditScore: 600,
          OriginationFee: "0.99% to 8.99%",
          Checkprocessingfee: "$7",
          Dotheyallowacosigner: "No",
          Latefee: "$15",
          Timetofund: "As soon as 1 - 3 business days after successful verification",
          Bestfor: "close rates if pre-approved",
        },
      ],
  },
  {
    id: 7,
    img: "/universallogo.svg",
    rating: 4.3,
    APR: "11.69-35.99%",
    loanTerm: "3, 5, or 7 years",
    loanAmount: "Up to $50,000",
    details: [
        {
          title: "Universal Credit",
          Prepaymentpenalty: "None",
          Unsuccessfulpaymentfee: "$1",
          MinimumCreditScore: 560,
          OriginationFee: "5.25% - 9.99%",
          Checkprocessingfee: "None",
          Dotheyallowacosigner: "No",
          Latefee: "$10",
          Timetofund: "As soon as 1 business day after acceptance",
          Bestfor: "Debt consolidation loans for bad credit",
        },
      ],
  },
  {
    id: 8,
    img: "/happymoneylogo.svg",
    rating: 3.8,
    APR: "11.72-24.67%",
    loanTerm: "2-5 Years",
    loanAmount: "Up to $40,000",
    details: [
        {
          title: "Happy Money ",
          Prepaymentpenalty: "None",
          Unsuccessfulpaymentfee: "None",
          MinimumCreditScore: 640,
          OriginationFee: "2% to 5%",
          Checkprocessingfee: "None",
          Dotheyallowacosigner: "No",
          Latefee: "None",
          Timetofund: "As soon as 2 - 5 business days after verification",
          Bestfor: "Consolidating credit card debt, boosting your credit score",
        },
      ],
  },
  {
    id: 9,
    img: "/bhgmoneylogo.svg",
    rating: 4,
    APR: "13.39-21.38%",
    loanTerm: "3-10 Years",
    loanAmount: "Up to $200,000",
    details: [
        {
          title: "BHG Money",
          Prepaymentpenalty: "None",
          Unsuccessfulpaymentfee: "None",
          MinimumCreditScore: 660,
          OriginationFee: "2% to 4%",
          Checkprocessingfee: "None",
          Dotheyallowacosigner: "Yes",
          Latefee: "If 15 or more days late, borrower may be charged 5.00% of the outstanding payment or $40 whichever is less.",
          Timetofund: "Funding in as few as 5 days",
          Bestfor: "Large personal loans",
        },
      ],
  },
  {
    id: 10,
    img: "/reachlogo.svg",
    rating: 4.5,
    APR: "14.30-35.99%",
    loanTerm: "2-5 Years",
    loanAmount: "Up to $40,000",
    details: [
        {
          title: "Reach Financial",
          Prepaymentpenalty: "None",
          Unsuccessfulpaymentfee: "$25",
          MinimumCreditScore: 640,
          OriginationFee: "4% to 8%",
          Checkprocessingfee: "None",
          Dotheyallowacosigner: "No",
          Latefee: "$15",
          Timetofund: "90% funded within a day",
          Bestfor: "Small loan amounts from online lenders",
        },
      ],

  },
  {
    id: 11,
    img: "/onemainlogo.svg",
    rating: 3.9,
    APR: "18.00-35.99%",
    loanTerm: "2-5 Years",
    loanAmount: "Up to $20,000",
    details: [
        {
          title: "OneMain Financial ",
          Prepaymentpenalty: "None",
          Unsuccessfulpaymentfee: "$10 to $50",
          MinimumCreditScore: 620,
          OriginationFee: "$25 to $500",
          Checkprocessingfee: "None",
          Dotheyallowacosigner: "Yes",
          Latefee: "$5 - $30",
          Timetofund: " As soon as 1 - 2 days after acceptance",
          Bestfor: "Personal loans for bad credit",
        },
      ],
  },
];

export default lenders;
