const options = [
  { value: "", label: "State", isDisabled: true },
  { value: "1", label: "Alabama" },
  { value: "2 ", label: "Alaska" },
  { value: "3", label: "Arizona" },
  { value: "4", label: "Arkansas" },
  { value: "5", label: "California" },
  { value: "6", label: "Colorado" },
  { value: "6", label: "Connecticut" },
  { value: "6", label: "Delaware" },
  { value: "6", label: "District of Columbia" },
  { value: "6", label: "Florida" },
  { value: "6", label: "Georgia" },
  { value: "6", label: "Hawaii" },
  { value: "6", label: "Idaho" },
  { value: "6", label: "Illinois" },
  { value: "6", label: "Indiana" },
  { value: "6", label: "Iowa" },
  { value: "6", label: "Kansas" },
  { value: "6", label: "Kentuckey" },
  { value: "6", label: "Louisiana" },
  { value: "6", label: "Maine" },
  { value: "6", label: "Maryland" },
  { value: "6", label: "Massachusetts" },
  { value: "6", label: "Michigan" },
  { value: "6", label: "Minnesota" },
  { value: "6", label: "Mississippi" },
  { value: "6", label: "Missouri" },
  { value: "6", label: "Montana" },
  { value: "6", label: "Nebraska" },
  { value: "6", label: "Nevada" },
  { value: "6", label: "New Hampshire" },
  { value: "6", label: "New Jersey" },
  { value: "6", label: "New Mexico" },
  { value: "6", label: "New York" },
  { value: "6", label: "North Carolina" },
  { value: "6", label: "North Dakota" },
  { value: "6", label: "Ohio" },
  { value: "6", label: "Oklahoma" },
  { value: "6", label: "Oregon" },
  { value: "6", label: "Pennsylvania" },
  { value: "6", label: "Rhode Island" },
  { value: "6", label: "South Carolina" },
  { value: "6", label: "South Dakota" },
  { value: "6", label: "Tennessee" },
  { value: "6", label: "Texas" },
  { value: "6", label: "Utah" },
  { value: "6", label: "Vermont" },
  { value: "6", label: "Virginia" },
  { value: "6", label: "Washington" },
  { value: "6", label: "West Virginia" },
  { value: "6", label: "Wisconsin" },
  { value: "6", label: "Wyoming" },

];

export default options;
